name: Publish to GitHub Packages

on:
  release:
    types: [published] 

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          server-id: github 

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x ./mvnw

      - name: Deploy to GitHub Packages
        run: ./mvnw deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          